config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin
  devise_for :employers

  root to: 'landing_pages#show'

  resource :landing_page, :only => [:show, :create]
  
  resources :jobs do
    resources :charges
  end
  
  resources :employers do
    resources :adverts
  end

  resources :orders
  
  resources :users do
    resources :submissions
  end  

end

app/models/job.rb
class Job < ActiveRecord::Base
	
	validates :advert_title, presence: true, length: { maximum: 40, minimum: 5 }
	validates :company, presence: true, length: { maximum: 40, minimum: 3 }
	validates :address, presence: true
	validates :wage, numericality: { only_integer: true }
	validates :email, format: { with: /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/ }

	belongs_to :employer


	geocoded_by :address
	after_validation :geocode
	# after_destroy :send_cancellation_email

	# def send_cancellation_email
 #  	JobMailer.cancellation(self).deliver
 #  end

end

app/controllers/jobs_controller.rb
	class JobsController < ApplicationController

	before_action :authenticate_employer!, except: [:index, :show]

	def index
		#puts params
		if params[:refined]
			filtered_by(params)
			@max_distance = params[:distance]
			# @max_distance = 10
			render 'index', content_type: :json
		else
			@jobs = Job.all
		end
		@submission = Submission.new
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(job_params)

		if @job.valid?
			@job.employer = current_employer
			@job.save
			redirect_to new_job_charge_path(@job)
		else
			flash[:notice] = 'There are some errors in your form'
			render 'new'
		end

	end

	def show
		@job = Job.find params[:id]
	end

	def update
		job = Job.find params[:id]
		job.update(job_params)
		redirect_to employer_adverts_path(job)
	end

	private

	def job_params
		params[:job].permit(:advert_title, :category, :company, :full_time, :detail, :address, :wage, :email, :phone)
	end

	def filtered_by(params)
		job_search_array = [params[:bar_box], params[:cafe_box], params[:hotel_box], params[:restaurant_box], params[:retail_box], params[:pub_box]].compact
		wage_range = params[:wage].to_i..100#params[:wage][1].to_i
		if (params[:full_time] == "true") || (params[:full_time] == "false")
			@jobs = Job.where({ category: job_search_array, wage: wage_range, full_time: params[:full_time] })
		else
			@jobs = Job.where({ category: job_search_array, wage: wage_range })			
		end
	end
	
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job_application_modal.html.erb
<div class="modal fade in" id="job_application">

	<div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h2>Job Application form</h2>
	</div>

	<div class="modal-body">
		<%= form_for @submission, url: user_submissions_path(current_user) do |s| %>

		<div>
			<p class="modal_form"><%= s.label :message, "To:", :class => 'form_control' %></p>
			<%= s.email_field :email, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= s.label :message, "Brief cover note:", :class => 'form_control' %></p>
			<%= s.text_area :message, :autofocus => true, class: 'form-control' %>
		</div>

		<p class="modal_form">CV preview:</p>
		<%= image_tag current_user.cv.url(:thumb), class: 'uploaded-cv' %>


		<p class="modal_form">
			<%= s.hidden_field :cv, :value => current_user.cv.url %>
			<%= s.submit "Submit to employer", :class => 'btn btn-small' %>
		</p>

		<% end %>
	</div>
</div>

<div class="modal fade in" id="submission_confirmation">

	<div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h2>We have emailed your submission to the employer!</h2>
	</div>
	
</div>

app/views/jobs/_new_job_modal.html.erb
<div class="modal fade in" id="job_new">

	<div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h2>Enter a job advert!</h2>
	</div>

	<div class="modal-body">
		<%= form_for job do |j| %>

		<div>
			<p class="modal_form"><%= j.label :advert_title %></p>
			<%= j.text_field :advert_title, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= j.label :category %>:</p>
			<%= j.select :category, ['Bar', 'Restaurant', 'Hotel', 'Retail', 'Cafe', 'StripClub'], class: 'form-control'%><br>
		</div>

		<div>
			<p class="modal_form"><%= j.label :company %></p>
			<%= j.text_field :company, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= j.label :full_time %>:</p>
			<%= j.select :full_time, ['Full Time', 'Part Time'], class: 'form-control' %><br/>
		</div>

		<div>
			<p class="modal_form"><%= j.label :detail %></p>
			<%= j.text_area :detail, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= j.label :address %></p>
			<%= j.text_field :address, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= j.label "Wage (£ per hour)" %></p>
			<%= j.text_field :wage, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= j.label :email %></p>
			<%= j.email_field :email, :autofocus => true, class: 'form-control' %>
		</div>

		<div>
			<p class="modal_form"><%= j.label :phone %></p>
			<%= j.telephone_field :phone, :autofocus => true, class: 'form-control' %>
		</div>

		<p class="modal_form">
			<%= j.submit 'Post a job', :class => 'btn btn-small' %>
		</p>

		<% end %>
	</div>

</div>

app/views/jobs/index.html.erb
<% if current_user %>
  <%= render "jobs/job_application_modal" %>
<% end %>
<%= render "devise/sessions/login_modal" %>

<div class="container-fluid">

	<div class="col-md-7 col-sm-6 hidden-xs jobpageleftside">
		<form class="search_box" class='index_page_jobs_search' method="post">
			<span class="glyphicon glyphicon-search"></span>
			<input type="text" class="searchTextField" placeholder="Find a job in...">		
			<input type="submit" style='display:none' value="Search">
		</form>

  	<div id="map_canvas">
	    <div id="map"></div>
	  </div>

	</div>

	<div class="col-md-5 col-sm-6 col-xs-12" id="jobpagerightside">

	<div class="second_search">
		<form class="search_box" class='index_page_jobs_search' method="post">
			<span class="glyphicon glyphicon-search"></span>
			<input type="text" class="searchTextField" placeholder="Find a job in...">		
			<input type="submit" style='display:none' value="Search">
		</form>
	</div>

<div class="panel-group" id="accordion">

	<div id="panel1" class="panel-collapse collapse">
			<div class="panel-body">
			

<aside class="jobs_filter">

			<div class="job_type_filter">
			<%= form_tag '/jobs', method: 'get', id: 'filter_form' do %>

				<div class="row" id="test">
					<div class="filter col-md-2 col-sm-2 col-xs-2"> 
						<div class="label"><%= label_tag(:bar_box, "Bar", :class => "checkbox-inline") %></div>
						<div class="bar_slider"><%= check_box_tag(:bar_box, 'Bar', true, :class => "switchery") %></div>
					</div>
					<div class="filter col-md-2 col-sm-2 col-xs-2">
						<div class="label"><%= label_tag(:pub_box, "Pub", :class => "checkbox-inline") %></div>
						<div class="strip_slider label"><%= check_box_tag(:pub_box, 'Pub', true, :class => "switchery") %></div>
					</div>
					<div class="filter col-md-2 col-sm-2 col-xs-2">
						<div class="label"><%= label_tag(:cafe_box, "Cafe", :class => "checkbox-inline") %></div>
						<div class="cafe_slider"><%= check_box_tag(:cafe_box, 'Cafe', true, :class => "switchery") %></div>
					</div>
					<div class="filter col-md-2 col-sm-2 col-xs-2">
						<div class="label"><%= label_tag(:hotel_box, "Hotel", :class => "checkbox-inline") %></div>
						<div class="hotel_slider"><%= check_box_tag(:hotel_box, 'Hotel', true, :class => "switchery") %></div>
					</div>
					<div class="filter col-md-2 col-sm-2 col-xs-2">
						<div class="label"><%= label_tag(:restaurant_box, "Restaurant", :class => "checkbox-inline") %></div>
						<div class="restaurant_slider"><%= check_box_tag(:restaurant_box, 'Restaurant', true, :class => "switchery") %></div>
					</div>
					<div class="filter col-md-2 col-sm-2 col-xs-2">
						<div class="label"><%= label_tag(:retail_box, "Retail", :class => "checkbox-inline") %></div>
						<div class="retail_slider"><%= check_box_tag(:retail_box, 'Retail', true, :class => "switchery") %></div>
					</div>
				</div>

				<div class="row" id="test2">
					<div class="filter col-md-4 col-sm-4 col-xs-4">
						<div class="label"><%= label_tag(:full_time, "Full Time / Part Time") %></div>
						<%= select_tag(:full_time, options_for_select([['Full Time', true], ['Part Time', false], ['Both', :both]]), :class => "form-control full_time_select_box") %>
					</div>
					<div class="filter col-md-4 col-sm-4 col-xs-4">
						<div class="label"><LABEL for="wage_slider">Min Pay(PerHour) </LABEL></div>
						<div class="wage_slider"><input id="wage_slider" data-slider-id='wageSlider' type="text" data-slider-min="0" data-slider-max="20" data-slider-step="0.5" data-slider-value="6"/></div>
					</div>

					<div class="filter col-md-4 col-sm-4 col-xs-4">
						<div class="label"><LABEL for="distance_slider">Distance(kms) </LABEL></div>
						<div class="distance_slider"><input id="distance_slider" data-slider-id='distanceSlider' type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="5"/></div>
					</div>

				</div>


				<div class="col-md-12 col-sm-12 col-xs-12" id="test5">
					<%= hidden_field(:refined, value: true) %>
					<div class="search_button"><%= submit_tag 'Refine Search', :class => 'btn btn-lg btn-success' %></div>
					<% end %>
				</div>

		</aside>


			
			</div>
		</div>

	<div class="panel panel-default">
		<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel1">

		<div class="panel-heading">
		<h4 class="panel-title">
		Search Filters<span class="glyphicon glyphicon-chevron-down"></span><span class="glyphicon glyphicon-chevron-up"></span>
		</h4>
		</div>

		</a>
		
	</div>
</div>

<% if Job.any? %>

		<aside class="advert_column">
			
		</aside>
	</div>

	<template id='individual_job_advert'>
		<div class='advert_info'>
			<div class="info row" id='openlink{{ linkid }}'>
				<a href='#'>
					<div class='category col-md-2 col-sm-2 col-xs-2'><img src='{{ category_src }}'></div>
					<div class='wage col-md-2 col-sm-2 col-xs-2'><span class="wage">£{{ wage }}</span></br> p.h.</div>
					<div class='company col-md-3 col-sm-3 col-xs-3'>
						<div class='job_title'>{{ advert_title }}</div>
						<div class='company_name'><span class"companyname">{{ company }}</span></div>
					</div>
					<div class='distance col-md-3 col-sm-3 col-xs-3'>
						<div class='distance_location'> <span class"distance">{{ distance }}</span> km</div>
						<div class='distance_title'>(distance)</div> 
					</div>
					<div class='full_time col-md-2 col-sm-2 col-xs-2'><img src='{{ hours_src }}'></div>
				</a>
			</div>

			<div class="more_info row" id='closelink{{ linkid }}'>
					<div class='detail col-md-8 col-sm-8 col-xs-8'>{{ detail }}</div>
					<div class='apply col-md-2 col-sm-2 col-xs-2 btn btn-default'>
						<% if user_signed_in? %>
						<%= link_to 'Apply now', "#job_application", "data-toggle" => "modal", "data-email" => '{{ email }}', class: 'apply-link' %>
						<% else %>
						<%= link_to 'Apply now', "#user_login", "data-toggle" => "modal", "data-email" => '{{ email }}', class: 'apply-link' %>
						<% end %>
					</div>
				<a href='#'>
					<div class="close-div col-md-2 col-sm-2 col-xs-2"><span class="glyphicon glyphicon-remove-circle"></span></div>
				</a>
			</div>
		</div>
	</template>


	<template id='pop_up_job_advert' >
		<div class='info_window'>
			<ul>	
				<li> <span class="adtitle">{{ advert_title }}</span> </li>
				<li>	{{ company }} </li>
				<li>	£{{ wage }} p.h </li>
				<li>	{{ hours }} </li>
				<li><span class="telephone">Tel:</span> {{ phone }} </li>				
				<!-- not 100% working - removed for heroku -->
				<!-- <li> <a href='jobs#job_application' data-toggle="modal" data-email='{{ email }}' id='apply-link'>Apply now!</a></li> -->
				
			</ul>
		</div>
	</template>

<% else %>

	No jobs inserted yet.

<% end %>

	<script>
var elems = Array.prototype.slice.call(document.querySelectorAll('.switchery'));

elems.forEach(function(html) {
  var switchery = new Switchery(html);
});
	</script>

	<script>
	$('#ex1').slider({
	formater: function(value) {
		return 'Current value: ' + value;
	}
});
	</script>


</div>

app/views/jobs/new.html.erb
<%= form_for @job do |job| %>
  <%= job.label :advert_title %>
  <%= job.text_field :advert_title %><br/>

  <%= job.label :category %>:
  <%= job.select :category, ['Bar', 'Restaurant', 'Hotel', 'Retail', 'Cafe', 'StripClub'] %><br/>

  <%= job.label :company %>:
  <%= job.text_field :company %><br/>

  <%= job.label :full_time %>:
  <%= job.select :full_time, ['Full Time', 'Part Time'] %><br/>

  <%= job.label :detail %>:
  <%= job.text_area :detail %><br/>

  <%= job.label :address %>:
  <%= job.text_field :address %><br/>

  <%= job.label :wage %>:
  <%= job.text_field :wage %><br/>

  <%= job.label :email %>:
  <%= job.email_field :email %><br/>

  <%= job.label :phone %>:
  <%= job.telephone_field :phone %><br/>

  <%= job.submit 'Post a job' %>
<% end %>