config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin
  devise_for :employers

  root to: 'landing_pages#show'

  resource :landing_page, :only => [:show, :create]
  
  resources :jobs do
    resources :charges
  end
  
  resources :employers do
    resources :adverts
  end

  resources :orders
  
  resources :users do
    resources :submissions
  end  

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController

	def index
		@employer = current_employer
		@adverts = @employer.jobs
	end

	def edit
		@job = Job.find params[:id]
	end

	def destroy
		job = Job.find params[:id]
		job.destroy
		redirect_to '/' #change this redirect to if other adverts > employer_adverts_path, if not post advert page

	end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/views/adverts/edit.html.erb
<div id="employer_job_edit">
  <%= form_for @job do |job| %>
    <%= job.label :advert_title %>
    <%= job.text_field :advert_title %><br/>

    <%= job.label :category %>:
    <%= job.select :category, ['Bar', 'Restaurant', 'Hotel', 'Retail', 'Cafe'] %><br/>

    <%= job.label :company %>:
    <%= job.text_field :company %><br/>

    <%= job.label :full_time %>:
    <%= job.select :full_time, ['Full Time', 'Part Time'] %><br/>

    <%= job.label :detail %>:
    <%= job.text_area :detail %><br/>

    <%= job.label :address %>:
    <%= job.text_field :address %><br/>

    <%= job.label :wage %>:
    <%= job.text_field :wage %><br/>

    <%= job.label :email %>:
    <%= job.email_field :email %><br/>

    <%= job.label :phone %>:
    <%= job.telephone_field :phone %><br/>

    <%= job.submit 'Update advert' %>
  <% end %>
</div>

app/views/adverts/index.html.erb
<div class="container">

	<h1 class = 'advert-head'>Welcome, <%= current_employer.email %>.</h1>

	<% if @adverts.any? %>
		<h2 class = 'advert-top'>Your adverts on <span class="logo-w">w<span><span class="glyphicon glyphicon-map-marker"></span><span class="logo-rk">rk</span><span class="logo-map">map</span>:</h2>
		<ul>
		<% @adverts.each do |advert| %>
			<h2 class = 'advert-line'><li><%= advert.advert_title %> - <%= advert.category %> - <%= advert.address %> - <%= advert.wage %>£ / hour</li></h2>
			<p class = 'advert-menu'><%= link_to 'Edit advert', edit_employer_advert_path(@employer, advert) %> - <%= link_to 'Remove advert', employer_advert_path(@employer, advert), method: 'delete' %></p>

		<% end %>
		</ul>
	<% else %>

		<h2>You don't have adverts, for now.</h2>
		
	<% end %>

	<h2><%= link_to 'Why not add one?', "#job_new", "data-toggle" => "modal" %></h2>


</div>