config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin
  devise_for :employers

  root to: 'landing_pages#show'

  resource :landing_page, :only => [:show, :create]
  
  resources :jobs do
    resources :charges
  end
  
  resources :employers do
    resources :adverts
  end

  resources :orders
  
  resources :users do
    resources :submissions
  end  

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


def new
  @job = Job.find(params[:job_id])
end

def create
  # Amount in cents
  # puts session[:temp_job]

  @job = Job.find(params[:job_id])
# working out how to create a new order object with a successful charge here.
  # @order = Order.create()
  @amount = 500

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'gbp'
  )

  @job.paid = true
  @job.save
  Order.create(employer: current_employer, job: @job)

flash[:notice] = "Thanks fo your payment!"
redirect_to "/employers/#{current_employer.id}/adverts"

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_job_charge_path(@job)
end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
<div class="container">

	<h1 class = 'advert-head'>Fee for adding this advert, with details:</h1>
	<h2 class = 'advert-line'><li><%= @job.advert_title %> - <%= @job.category %> - <span class='advert-address'><%= @job.address %></span> - £<%= @job.wage %> / hour</li></h2>

	<div id="map-advert"></div>
	
	<%= form_tag job_charges_path(@job) do %>
	<article>
		<label class="amount">
			<h2 class = 'advert-line'><span>Cost of your ad: £5.00</span><h2 class = 'advert-line'>
			</label>
		</article>

		<script src="https://checkout.stripe.com/checkout.js" id="stripetestbutton" class="stripe-button"
		data-key="<%= Rails.application.secrets.stripe_public_key %>"
		data-description="Payment for your ad"
		data-amount="500"
		data-currency="GBP">
	</script>
	<% end %>
	
</div>