config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin
  devise_for :employers

  root to: 'landing_pages#show'

  resource :landing_page, :only => [:show, :create]
  
  resources :jobs do
    resources :charges
  end
  
  resources :employers do
    resources :adverts
  end

  resources :orders
  
  resources :users do
    resources :submissions
  end  

end

app/views/layouts/_navbar_modal.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a a class="navbar-brand" href="/jobs"><span class="logo-w">w<span><span class="glyphicon glyphicon-map-marker"></span><span class="logo-rk">rk</span><span class="logo-map">map</span>
        </a>
      </div>
      <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
         <% if employer_signed_in? %>
         <li><%= link_to 'Edit registration', "#employer_edit", "data-toggle" => "modal", class: 'landing_page_login_link'%></li>
         <li><%= link_to 'Create a job', "#job_new", "data-toggle" => "modal", class: 'landing_page_login_link' %></li>
         <li><%= link_to 'My adverts', employer_adverts_path(current_employer), class: 'landing_page_login_link' %></li>
         <li><%= link_to 'Logout', destroy_employer_session_path, :method => :delete, class: 'landing_page_login_link'%></li>
         <% elsif user_signed_in? %>
         <li><a class='landing_page_login_link'>Welcome, <%= current_user.name %></a></li>
         <li><%= link_to 'Edit registration', '#user_edit', "data-toggle" => "modal", class: 'landing_page_login_link'%></li>
         <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'landing_page_login_link'%></li>
         <% else %>
         <li><%= link_to 'Hiring? Post a job!', "#employer_login", "data-toggle" => "modal", class: 'landing_page_login_link' %></li>
         <li><%= link_to 'Job hunting? Sign in!', "#user_login", "data-toggle" => "modal", class: 'landing_page_login_link' %></li>
         <% end %>
         <%= javascript_include_tag 'application' %>
       </ul>
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= favicon_link_tag '/favicon.ico' %>
<title>WorkMap</title>
<!-- <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script> -->
<script language="JavaScript" type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=geometry,places&sensor=false"></script>
<script language="JavaScript" type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js"></script>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= csrf_meta_tags %>
</head>

<body>
	<%= render "devise/sessions/login_modal" %>
	<%= render "devise/registrations/signup_modal" %>
	<%= render "jobs/new_job_modal" %>
	<% if current_employer %>
	<%= render "devise/registrations/employer_edit_modal" %>
	<% end %>
	<% if current_user %>
	<%= render "devise/registrations/user_edit_modal" %>
	<% end %>
	<%= render "layouts/navbar_modal" %>

	<% flash.each do |type, message| %>
	<div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true" class='close-alert'>&times;</span><span class="sr-only">Close</span></button>
		<%= message %>
	</div>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/layouts/landingpage.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WorkMap</title>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag 'jquery' %>
	<%= javascript_include_tag 'landing_pages' %>
</head>

<body>

<%= render "devise/sessions/login_modal" %>
<%= render "devise/registrations/signup_modal" %>
<%= render "jobs/new_job_modal" %>
<% if current_user %>
  <%= render "devise/registrations/user_edit_modal" %>
<% end %>
<% if current_employer %>
  <%= render "devise/registrations/employer_edit_modal" %>
<% end %>
<%= render "layouts/navbar_modal" %>

  

  <%= yield %>
</body>

</html>